version: "3.8"
services:
  caddy:
    image: caddy:2.5.2-alpine
    environment:
      MY_EMAIL: ${MY_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "caddy_data:/data/"
      - "caddy_config:/config/"
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
  app:
    image: rflix:latest
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "db_data:/var/lib/postgresql/data"
volumes:
  caddy_data:
  caddy_config:
